export const JSONLD_CONTEXT = {
  "@vocab": "https://epdagent.dev/vocab/",
  schema: "https://schema.org/",
  prov: "http://www.w3.org/ns/prov#",
  xsd: "http://www.w3.org/2001/XMLSchema#",
  EPD: "https://epdagent.dev/vocab/EPD",
  ProgramOperator: "https://epdagent.dev/vocab/ProgramOperator",
  declaredUnit: {
    "@id": "https://epdagent.dev/vocab/declaredUnit",
    "@type": "schema:QuantitativeValue",
  },
  programOperator: { "@id": "https://epdagent.dev/vocab/programOperator", "@type": "@id" },
  producer: { "@id": "https://epdagent.dev/vocab/producer", "@type": "@id" },
  verifier: { "@id": "https://epdagent.dev/vocab/verifier", "@type": "@id" },
  pcrReference: "https://epdagent.dev/vocab/pcrReference",
  epdNumber: "https://epdagent.dev/vocab/epdNumber",
  language: "https://epdagent.dev/vocab/language",
  filenamePattern: "https://epdagent.dev/vocab/filenamePattern",
  "schema:name": "https://schema.org/name",
  "schema:address": "https://schema.org/address",
  "schema:addressCountry": "https://schema.org/addressCountry",
  "schema:validFrom": { "@id": "https://schema.org/validFrom", "@type": "xsd:date" },
  "schema:validThrough": { "@id": "https://schema.org/validThrough", "@type": "xsd:date" },
  "schema:value": "https://schema.org/value",
  "schema:unitCode": "https://schema.org/unitCode",
  "prov:wasDerivedFrom": "http://www.w3.org/ns/prov#wasDerivedFrom",
  "prov:generatedAtTime": {
    "@id": "http://www.w3.org/ns/prov#generatedAtTime",
    "@type": "xsd:dateTime",
  },
} as const;
